### ISSUE TITLE
[feature]Fontのインポート(裏作業でやっときたい)

### ISSUE THREAD

**Issue by haruu11113** [haruu11113/nuxt-notion-blog#24]
## [概要]
多分google fontになると思う。
importして使える状態にしておきたい。

## [課題]

このissueが解決する課題
関連するissueや記事のurl

## [解決すること]

このissueによって改善する内容、ねらい

## [技術案・メモ]

開発の方針など検討したことなどを記載

**Comment by sakaaya** [comment]
@haruu11113 

https://zenn.dev/__south__373/articles/c7f7fbe4aed736

ここ見ながらやってみた
けどなんかHeaderの文字が変わらない、、、

見た目変わったのわかるように、https://fonts.google.com/specimen/M+PLUS+Rounded+1c?preview.size=18&sort=popularity&subset=japanese&noto.script=Jpan
を適用してみてる。
暇な時みてみて、お好みに変更ください🙏
Headerわかればまたコミットします。

Branchの紐付けがなんかうまくいかない問題もあります、、、
https://github.com/haruu11113/nuxt-notion-blog/pull/55

**Comment by sakaaya** [comment]
https://zenn.dev/taizo_pro/articles/4e62adae97440e
ここみて参考にした。

![image](https://github.com/haruu11113/nuxt-notion-blog/assets/118742514/98dfee28-c565-46ff-9729-b84e9ebdacab)
![image](https://github.com/haruu11113/nuxt-notion-blog/assets/118742514/88e462e3-d802-4300-b880-245936afd59d)

**Comment by sakaaya** [comment]
https://github.com/haruu11113/nuxt-notion-blog/pull/55/files#diff-433ba4a11cedb41d69c4eb458c8f3094e88e479caa923f9b5f683af4e89e749eR1
→Bの内容

https://github.com/haruu11113/nuxt-notion-blog/pull/55/files#diff-5977891bf10802cdd3cde62f0355105a1662e65b02ae4fb404a27bb0f5f53a07R21
→Aの内容


![Window_と_Noto_Sans_Japanese_-_Google_Fonts](https://github.com/haruu11113/nuxt-notion-blog/assets/118742514/33636aad-ed87-4758-825e-ad482cf4cfb2)
