### ISSUE TITLE
[feature]記事ごとに公開・非公開を設定できるようにする

### ISSUE THREAD

**Issue by KoichiroHino** [haruu11113/nuxt-notion-blog#25]
## [概要]
Notionの記事ごとに公開・非公開を設定できるようにする

## [課題]

- [ ] Notionのプロパティに公開・非公開を設定するプロパティを新規追加
- [ ] 記事一覧を取得する際に、追加した新規プロパティでフィルターをかける

- [ ] 公開設定は管理者ユーザのみができるようにしたい <= 外部の人もnotionにアクセス・記事作成できるが、僕たちしか公開プロパティをONにできない仕組み

## [解決すること]
Notionで執筆中の記事を公開することなく、編集できるようになる

## [技術案・メモ]

開発の方針など検討したことなどを記載

**Comment by KoichiroHino** [comment]
@haruu11113 
issue立ててみたけどこれで大丈夫そう？

**Comment by haruu11113** [comment]
@KoichiroHino いい感じ、さんきゅ！

**Comment by haruu11113** [comment]
@KoichiroHino @toshimaru0123 @sakaaya 
「公開設定は管理者ユーザのみができるようにしたい <= 外部の人もnotionにアクセス・記事作成できるが、僕たちしか公開プロパティをONにできない仕組み」

上記のToDoを足してみました。ユーザの権限管理とか、データベースの属性ごとにアクセス制限つけるとかって出来ますか？
要は公開・非公開パラメータは一部のユーザしか触れないようにしたいです。

（notionに詳しそうな人にメンションしてみた）

**Comment by sakaaya** [comment]
@haruu11113 
![image](https://github.com/haruu11113/nuxt-notion-blog/assets/118742514/0121bbbe-3316-41ac-998e-79fe0db97f67)

なんか少しみてみてたけど、有料版であればもう少し権限増やせるのかもしれないなーくらいしかわからなかったや。
https://www.notion.so/ja-jp/help/sharing-and-permissions#%E6%A8%A9%E9%99%90%E3%83%AC%E3%83%99%E3%83%AB
編集権限ならデータベース側の編集はできないような設定かもしれないなーくらいしかわからないけど。。。
