### ISSUE TITLE
[feature]indexページ(/index)をいい感じに作成

### ISSUE THREAD

**Issue by haruu11113** [haruu11113/nuxt-notion-blog#31]
## [概要]
Figmaのデザインをもとに作成する。
./pages/index.vue　をいい感じに作る

## [課題]

このissueが解決する課題
関連するissueや記事のurl

## [解決すること]

このissueによって改善する内容、ねらい

## [技術案・メモ]

開発の方針など検討したことなどを記載

**Comment by haruu11113** [comment]
1段目 @m-koga201003 
2段目 @sakaaya 
3段目 @toshimaru0123

**Comment by sakaaya** [comment]
![image](https://github.com/haruu11113/nuxt-notion-blog/assets/118742514/d794bf9e-ba0b-4c22-8e66-03902659f629)

なんとなくいい感じ！まではできたので一旦コミットしましたー

若干上よりなのと、
なんか無理やり描いてる感じしかないので、（フロントの実務経験はまだないので）この書き方ダメ、とかあったら教えてくれると助かります🙏
